pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                    git branch: 'master', url: 'https://github.com/jenkins-docs/simple-java-maven-app.git'
                    sh '''
                        #!/bin/bash
			sudo su -
                        pwd 
                        ls
                        echo "This is a BUILD stage"
                        mvn clean package
                    ''' 
            }
        }
    }
}
